### ISSUE TITLE
support `M.[ foo ]`, `M.[| foo |]`, etc. (PR#6054)

### ISSUE THREAD

**Issue by gasche** [camlp4/camlp4#10]
The syntax for local module open has been extended to other standard delimiters in trunk, following [bugreport 6054](http://caml.inria.fr/mantis/view.php?id=6054). Barring any last minute veto, this should make it into the next release, so it would be nice to add support in Camlp4 at some point.

**Comment by gasche** [comment]
I tried to have a look at how we may implement this, and it doesn't seem easy. The direct way is to duplicate the logic currently used to support `P.(`, namely the not-pretty [module_longident_dot_lparen](https://github.com/ocaml/camlp4/blob/trunk/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.ml#L1249), but this would occur quite a bit of code duplication. It may still be the most reasonable option, though, as other options could be invasive.

One approach I've been thinking of is to separate the delimiters-enclosed rules (but _not_ the `begin .. end` forms which are voluntarily not supported by this change) from the "simple" expression level into their own Camlp4 rule, turn `module_longident_dot_lparen` into a non-consuming test (à la [test_not_dot_nor_lparen](https://github.com/ocaml/camlp4/blob/trunk/camlp4/Camlp4Parsers/Camlp4OCamlParser.ml#L70)), and add both

```
  | e = delimited_expr -> e
  | test_longident_dot_delim; m = module_longident; "."; e delimited_expr ->
     <:expr< let open $m$ in $e$ >>
```

to simple expressions.

What do you think?

PS: there are a few `SELF` uses in the production rules for delimited expressions, but I assume changing them to `expr` does not change parsing behavior as they are, precisely, delimited by non-terminals.

**Comment by ghost** [comment]
Seems good to me. Do we even need `delimited_expr`? This should be enough:

``` ocaml
  | test_longident_dot_delim; m = module_longident; "."; e = SELF ->
     <:expr< let open $m$ in $e$ >>
```

**Comment by gasche** [comment]
But this makes you more accepting than the official grammar, doesn't it? (Maybe you can filter the extra stuff out in the Camlp4Ast2OCamlAst phase, but here I don't think you'll have enough information). Being too liberal is not satisfying because then people get used to that, and (besides the eventual surprise and upstream bugreport) make the life of Merlin developers a living hell.

**Comment by ghost** [comment]
> But this makes you more accepting than the official grammar, doesn't it?

Well if `test_longident_dot_delim` test for a delimiter then `e` is constrained.

**Comment by gasche** [comment]
Right, excellent! I may have a try at a patch later this week.
