### ISSUE TITLE
Release for 4.04

### ISSUE THREAD

**Issue by leahneukirchen** [camlp4/camlp4#114]
Will there be a proper release targetting OCaml 4.04 or are we supposed to just use the branch? Package maintainers such as me would prefer a stable tarball.

**Comment by ghost** [comment]
I did a release: https://github.com/ocaml/opam-repository/pull/7873

**Comment by leahneukirchen** [comment]
Thanks!

**Comment by kiniry** [comment]
I can't get ```ocamlp4``` installed on OS X.  brew contains ocaml 4.04.0.  ```opam install camlp4``` reports 
```
This version of Camlp4 is for OCaml 4.05 but you are using OCaml 4.04.0.
If building Camlp4 directly from git, use the 4.04 branch.
```
which is odd, given that 4.05 stable does not exist.  And none of this jives with https://opam.ocaml.org/packages/camlp4/ or http://www.ocaml.org/docs/install.html or especially https://caml.inria.fr/download.en.html

I'm grabbing a git clone now to see if ```trunk``` is 4.05...?

**Comment by kiniry** [comment]
Performing a clean re-install of opam from brew and then explicitly doing an ```opam update && opam upgrade``` forced the opam database refresh (which I had thought was automatically part of the original install) and, hence, visibility to the new merge.  camlp4 for 4.04 now installs.

**Comment by cef62** [comment]
I had the same issue, this thread saved me after a long research. Could be worth mentioning the clean install on some FAQ or documentation.
