### ISSUE TITLE
camlp4 fails to build with 4.04.0+spacetime

### ISSUE THREAD

**Issue by tim-felix-lange** [camlp4/camlp4#120]
When trying to build camlp4 with OCaml 4.04.0+spacetime compiler, it breaks with the following error message. Error occurs with opam and manual installation from git. 

```
+ /home/user/ocamlbrew/ocaml-4.03.0/.opam/4.04.0+spacetime/bin/ocamlopt.opt -c -g -safe-string -w a -I camlp4/import -I camlp4/config -I camlp4/boot -o camlp4/boot/camlp4boot.cmx camlp4/boot/camlp4boot.ml
File "camlp4/boot/camlp4boot.ml", line 1:
Error: I/O error: as -o 'camlp4/boot/camlp4boot.o' '/tmp/camlasm862539.s': Cannot allocate memory
Command exited with code 2.
Makefile:13: recipe for target 'byte' failed
make: *** [byte] Error 10
```

Trying to install on Debian Jessie Virtual Machine, 12GB Ram, Stack limit of 20.000
`Linux user 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux`

**Comment by gasche** [comment]
Thanks for the report! The problem has been reported as an ocaml compiler issue at [MPR#7435](https://caml.inria.fr/mantis/view.php?id=7435). I'm closing this one as a duplicate.
