### ISSUE TITLE
Error: Program camlp4oof not found in the tree or in PATH (context: default)

### ISSUE THREAD

**Issue by floydianslips** [camlp4/camlp4#137]
ocaml is all new to me and I am trying to compile a program using it. I can't seem to get past this issue. It happens whenever I try to install anything now. I am trying to install on a Rasperry Pi 3 running Raspian Stretch. I have tried to uninstall and reinstall camlp4 but alas to no avail. Any help is appreciated. Thanks.

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[lwt] Archive in cache
[lwt_ppx] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of lwt failed at "jbuilder build -p lwt -j 4".

#=== ERROR while installing lwt.3.2.1 =========================================#
# opam-version 1.2.2
# os           linux
# command      jbuilder build -p lwt -j 4
# path         /root/ocamlbrew/ocaml-4.05.0/.opam/system/build/lwt.3.2.1
# compiler     system (4.05.0)
# exit-code    1
# env-file     /root/ocamlbrew/ocaml-4.05.0/.opam/system/build/lwt.3.2.1/lwt-9459-1872ec.env
# stdout-file  /root/ocamlbrew/ocaml-4.05.0/.opam/system/build/lwt.3.2.1/lwt-9459-1872ec.out
# stderr-file  /root/ocamlbrew/ocaml-4.05.0/.opam/system/build/lwt.3.2.1/lwt-9459-1872ec.err
### stderr ###
# File "jbuild", line 1, characters 0-0:
# Warning: File META.lwt is both generated by a rule and present in the source tree.
# As a result, the rule is currently ignored, however this will become an error in the future.
# Delete file META.lwt to get rid of this warning.
# Error: Program camlp4oof not found in the tree or in PATH (context: default)

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
  ∗  install lwt_ppx 1.0.1
The following actions failed
  ∗  install lwt 3.2.1
No changes have been performed

=-=- lwt.3.2.1 troubleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> Lwt 4.0.0 will make some breaking changes in March 2018. See
     https://github.com/ocsigen/lwt/issues/453

**Comment by gasche** [comment]
You may be running a system switch, where opam tries to cohabitate with system-installed packages (check if `opam switch show` prints `system`). It may work better using an opam-specific switch with `opam switch install 4.06.1`.

**Comment by floydianslips** [comment]
Thanks a lot. That worked perfectly. Now on the next roadblock!
