### ISSUE TITLE
OCaml 4.07 compat?

### ISSUE THREAD

**Issue by andyli** [camlp4/camlp4#143]
Currently camlp4 can't be install with opam when using ocaml 4.07.0. Would you update it?

**Comment by gasche** [comment]
This is a good question/reminder, thanks!

We need to check whether the current camlp4 trunk builds with 4.07, and otherwise make the necessary changes -- usually corresponding to small type-definition changes in the OCaml AST -- and push them into a new branch.

**Comment by ghost** [comment]
I just check and trunk builds with 4.07, so we just need to do a new release

**Comment by ghost** [comment]
I submitted the release: https://github.com/ocaml/opam-repository/pull/12330

**Comment by gasche** [comment]
Thanks!

**Comment by andyli** [comment]
I verified it works now, thanks!
