### ISSUE TITLE
revised syntax not updated

### ISSUE THREAD

**Issue by blumens** [camlp4/camlp4#146]
I know the revised syntax is deprecated (as is camlp4) and I'm probably the only one still using it, but it would be nice if the revised syntax were updated to include newer features of OCaml like, for instance, inline records.

**Comment by gasche** [comment]
I'm afraid that nobody is willing to do the work of regularly updating the revised syntax parsers of Camlp4 to support new OCaml features. (One feature that I think would be very interesting to support is attributes and extension points, and even that didn't find the workforce it needed.) That is, unless you yourself would be willing to contribute such support?

On the other hand, I believe that [Camlp5](https://camlp5.github.io/doc/htmlc/revsynt.html) is more actively maintained than Camlp4. It may have implemented support for more recent OCaml features, although I understand that it is also on-demand. You should maybe get in touch with its maintainer, Daniel de Rauglaudre, if you need support for a specific new feature. (To be honest, I also think that your own willingness to contribute would also be more effective/appreciated on Camlp5 than Camlp4.)

(I'm "closing" this issue to mark that I don't believe this resolution will change, but commenting is still possible in the thread, please feel free to do so.)

Out of curiosity: who are you, or what kind of revised programs are you writing? I thought that Gérard Huet was the main OCaml programmer to have kept a large revised-syntax codebase, and I wasn't aware of other people (other than Daniel, and the occasional updates to the Camlp5 or Camlp4 codebase by other people) actively developing using it. Do you have a link to your current developments using the revised syntax?
