### ISSUE TITLE
can't install campl4@4.07+1 with esy

### ISSUE THREAD

**Issue by Et7f3** [camlp4/camlp4#152]
OS: windows 10
package manager: [esy](https://esy.sh)

log file: https://gist.github.com/Et7f3/2994b5b63106a264f508f84c87dd220a#file-failed_log-txt
minimal repro: https://gist.github.com/Et7f3/2994b5b63106a264f508f84c87dd220a#file-package-json

step to repdroduce:
- install esy
- download package.json in empty folder
- open cmd.exe
- travel to the folder that contain only package.json
- type `esy`

some note:
you can see the graph of dependencies in esy.lock/index.json
the first time it will build ocaml compiler so it is availabel inside esy: but once it is build: it will be faster.
other port it for windows with old OCaml see https://github.com/esy-ocaml/camlp4 I have tried to reproduce theese commits: don't help. From what I see: it only config path variable so others package can use it.
I use esy because it support native workflow with OCaml on windows.

Hello,
I have a project that use camlp4 and when i try to build I get some error.  I have added some information that might be helpful. If you want more info/test I am here.

Edit: esy build project in sandbox for me it is:
X:\usr\root\.esy\3_\b\opam__s__camlp4-opam__c__4.07+1-09660eb8\_build
because I have changed ESY__PREFIX var: if empty it will be %USERPROFILE%\\.esy

**Comment by gasche** [comment]
This looks like an issue with the way esy manages its directories and relocations, rather than a problem on the camlp4 side. (Or rather: fixing the issue may require changing some things in camlp4 to make esy's life easier, but the maintainers of camlp4 won't know what given that it depends on the internals of esy). Could you try reporting the issue to the esy people?

**Comment by Et7f3** [comment]
esy move file to special folder and copy all file inside it

It is strange that file is not empty

```
type "X:\usr\root\.esy\3_\b\opam__s__camlp4-opam__c__4.07+1-09660eb8\_build\camlp4\Camlp4\Debug.mli.depends"
camlp4/Camlp4/Debug.mli:
```

**Comment by Et7f3** [comment]
The problem is not esy but it is ocamlbuild. Dev version of ocamlbuild fix the build see https://github.com/ocaml/ocamlbuild/issues/299. I have asked to publish new version.
