### ISSUE TITLE
Package camlp4 has a bad versioning system

### ISSUE THREAD

**Issue by yannl35133** [camlp4/camlp4#157]
The algorithm to detect which version of camlp4 is incompatible with the way it is currently named :

Version camlp4.4.11+system is considered more up-to-date than camlp4.4.11+1, even if they are supposed to be the same version.

I don't know how to solve this issue best; I believe a system of virtual package with two dependencies according to whether the compiler is opam-installed or system wide could work, but I have no experience in making this work.

See [this bug](https://github.com/ocaml/opam-repository/issues/17511) in `opam-repository`

**Comment by ygrek** [comment]
I believe this is opam packaging issue
