### ISSUE TITLE
Stream module moving from OCaml stdlib to camlp-stream library

### ISSUE THREAD

**Issue by xavierleroy** [camlp4/camlp4#160]
Camlp4-generated parsers and printers rely on the Stream module from the OCaml standard library.  Some parsers also use the Genlex module as lexer.

The core OCaml development team is planning to remove the Stream and Genlex modules from the standard library, after a few releases where these modules will be marked as deprecated (https://github.com/ocaml/ocaml/pull/10482).

In parallel, a new library [camlp-streams ](https://github.com/ocaml/camlp-streams) providing the Stream and Genlex modules is already available and packaged in OPAM.

For a smooth transition, Camlp4 needs to be modified sooner than later to link the preprocessed code with the camlp-streams library.  It should suffice to change the META file to require the `camlp_streams` package.  OPAM dependencies will have to be updated as well.

Thanks for your attention.

**Comment by xavierleroy** [comment]
Last call for feedback before https://github.com/ocaml/ocaml/pull/10482 is merged.

**Comment by ygrek** [comment]
Thanks for an advance warning.
I don't have time to look into it now.
I trust your judgement and previous transitions experience that it is a workable plan :)

**Comment by rr0gi** [comment]
this was fixed in ed33f736e

**Comment by ygrek** [comment]
this was fixed in ed33f736e
