### ISSUE TITLE
Cut a release ?

### ISSUE THREAD

**Issue by samoht** [camlp4/camlp4#2]
Would it be possible to cut a first independent release of camlp4 ? We need this into opam-repository now that it has disappeared from trunk (see https://github.com/ocaml/opam-repository/issues/1446)

**Comment by ghost** [comment]
Can't the opam package use the development version of camlp4? At the moment the repo requires the trunk of ocaml to build, this means that if I do a release it won't build against any released version of ocaml, which might be confusing. If we really need a release, I can try to make it build against 4.01.

**Comment by samoht** [comment]
You are right, we can use a dev version of `camlp4` before the next OCaml is officially released and start identifying the packages which need camlp4 to compile.
