### ISSUE TITLE
Breaks when used with system compiler

### ISSUE THREAD

**Issue by whitequark** [camlp4/camlp4#30]
See https://travis-ci.org/whitequark/ocaml-ppx_protobuf#L222 for a detailed log.

Maybe related to #15.

**Comment by ghost** [comment]
It's just a permission problem. You do need to install camlp4 in `ocamlc -where` otherwise packages that don't use findlib are gonna break.

**Comment by whitequark** [comment]
Uh... but all other packages install just fine into `~/.opam/system`?

**Comment by ghost** [comment]
Yes, when they use ocamlfind. I haven't tested, but if we install camlp4 in `ocamlfind printconf destdir` instead of `ocamlc -where`, you can't do `ocamlc -I +camlp4` anymore.

**Comment by whitequark** [comment]
I'm pretty sure the `camlp4` _opam package_ should not attempt to write into system dirs. I mean, I want my CI working properly, and even on a desktop that's useful.

**Comment by ghost** [comment]
I think the solution is to change the opam file of camlp4 to set `LIBDIR` when doing `make install`.

**Comment by ghost** [comment]
For the record, that's what is done for camlp5.

**Comment by whitequark** [comment]
Ok, still broken, now because of `-I +camlp4`... do we really care about non-ocamlfind packages more than about working Travis?

I'm suggesting PR #33.

**Comment by avsm** [comment]
There will be minor fallout, but easily detected in the bulk builds for non-ocamlfind camp4 users.  Any reason not to install camlp4 as a normal ocamlfind package in OPAM?

**Comment by ghost** [comment]
I don't have strong objections to installing camlp4 with ocamlfind. Basically my impression was that it should stay compatible as much as possible, no point it creating more work for people for a dying project.

Anil, if you are confident we can catch all uses of `-I +camlp4`, I'm fine updating camlp4 to be installed as a regular ocamlfind package.

**Comment by whitequark** [comment]
Ping? This prevents testing any of my packages on CI with 4.02.

**Comment by avsm** [comment]
On 12 May 2014, at 10:44, Jérémie Dimino notifications@github.com wrote:

> Anil, if you are confident we can catch all uses of -I +camlp4, I'm fine updating camlp4 to be installed as a regular ocamlfind package.
> 
> I can take a shot at this from the bulk logs at https://github.com/ocaml/opam-bulk-logs.

Note that packagers of ocaml can still choose to install camlp4 in its old location -- I don't see a better option for OPAM users, since we cannot require sudo to install to the system area.

-anil

**Comment by whitequark** [comment]
Any update on this?

**Comment by whitequark** [comment]
Ping.

**Comment by avsm** [comment]
@diml -- I'm happy to test installing camlp4 with ocamlfind, if you can cook up the diff upstream.  I think it's the only way to ensure that we can continue to work non-root with a system-installed compiler

**Comment by ghost** [comment]
@avsm, I've created a branch install-with-ocamlfind

**Comment by whitequark** [comment]
Ping?

**Comment by avsm** [comment]
Woops, I see the `install-with-ocamlfind` branch exists, but isn't merged (c.f. my comment in #33).  Is this branch up-to-date with the latest 4.02 branch to try out?  I do think we should shift to this model before release, and fix up build systems in-tree.

**Comment by ghost** [comment]
Yes it is up to date.

**Comment by ghost** [comment]
I think I'll just make the change. That will force packages that use camlp4 without ocamlfind to start using ocamlfind.

**Comment by avsm** [comment]
Sounds good.  Can you tag a concrete revision of the branch so we can replace the `git://` url in the camlp4 repo with the RC version?  I assume changes are unlikely from now until 4.02.0 release.

**Comment by ghost** [comment]
Done. I tagged 4.02.0+rc1.
