### ISSUE TITLE
Fails to install (ocamlfind cannot find camlp4/META)

### ISSUE THREAD

**Issue by mvduin** [camlp4/camlp4#44]
Installation fails with `ocamlfind: camlp4/META: No such file or directory`.  While the file `camlp4/META` has been created by the top-level Makefile, ocamlfind is invoked inside `_build/camlp4` and fails to locate it there.

Having the Makefile produce the META file inside _build/camlp4/ instead of inside camlp4/ and changing the relevant line in build/install.sh into
`ocamlfind install camlp4 META \`
fixed the issue for me, but I have no idea how all this is supposed to work and whether this is the appropriate way to fix it.
- linux-amd64
- opam 1.2 from git (but had the same issue with 1.1)
- ocaml 4.02.0+trunk
- ocamlfind 1.5.2
- camlp4 4.02.0

**Comment by avsm** [comment]
This is fixed in #43
