### ISSUE TITLE
camlp4 should not break "-I +camlp4" compatibility

### ISSUE THREAD

**Issue by lefessan** [camlp4/camlp4#45]
What about OCaml developers who do not use ocamlfind ?

**Comment by avsm** [comment]
I've just raised this question on caml-devel to get more opinions.  Not clear what the right solution is, so I'm pasting it below in case anyone has opinions.

> Jeremie and I have been packaging up camlp4 for distribution with the 4.02 RC, and a little question came up that could use a broader opinion from the development team fairly urgently.
> 
> There are two distribution channels for the new camlp4: via OPAM (source users) and via OS binary packaging (distro users).  In the latter case, camlp4 can be installed in exactly the same way as it is today, beside the compiler so that adding `-I +camlp4` is sufficient to pick up the library).
> 
> With OPAM, things get a little more complex. There are two types of compiler switches that are supported: a system compiler, and a custom-compiled compiler.  Installing camlp4 via OPAM requires that the installation operate without root privilege.  If a custom compiler switch is used, this isn't a problem since the compiler binaries live under ~/.opam/<switch>/{bin,lib}.
> 
> It's the system switch that is problematic for installing camlp4, since we cannot modify the (root owned) system compiler installation, and must stick OCaml somewhere inside ~/.opam. The most obvious way to work around this is by installing it via ocamlfind, which is what the camlp4-4.01.0+rc1 tagged version does.
> 
> Using ocamlfind brings a couple of drawbacks though:
> - Most obviously, any use of camlp4 now requires ocamlfind to be used to locate camlp4 in the pp path.  One could argue this isn't too bad since it brings the tool into line with the vast majority of other packages that do use it (including the emerging set of ppx tools).
> - Unfortunately, ocamlbuild's builtin tags for rules hardcode a `-I +camlp4` as far as I can tell, so porting some of these requires imposing a -use-ocamlfind and possibly adding custom rules, _or_ patching ocamlbuild quite late in the RC cycle (i.e. tomorrow, presumably).
> 
> Any opinions on the best way to fix this with minimal disruption?  We could revert the ocamlfind dependency, or see if there's some symlink magic that would let all three setups work (distro, OPAM-system and OPAM-custom).  Here's hoping the wisdom of crowds finds an easy solution that doesn't leave one of these folks high and dry :-)

**Comment by Chris00** [comment]
Did not think much about it but [here is a suggestion](https://github.com/ocaml/opam-repository/pull/2503#issuecomment-53622652).

**Comment by avsm** [comment]
The released version preserves non-ocamlfind operation as requested, so closing
