### ISSUE TITLE
camlp4 + toplevel = hang

### ISSUE THREAD

**Issue by xiey8** [camlp4/camlp4#48]
I ran into the following problem after upgrading to 4.02. As soon as I load the
camlp4o.cma in the toplevel, it doesn't seem to want to parse statements as
they're typed in anymore -- ";;" has no effect and I had to type several ^D in a
row to get the statement parsed.

4.01 is fine. Utop is fine.  It's only been a problem for me under plain
toplevel since 4.02.

Thanks!

Steps to Reproduce:

```
        OCaml version 4.02.1+dev0-2014-08-29

# #load "dynlink.cma";;
# #load "camlp4o.cma";;
        Camlp4 Parsing version 4.02.1+dev0-2014-08-29

#1;;
  3;;




^D
^D
^D
^D
^D
^D
^D
- : int = 1
```

**Comment by rand00** [comment]
I have the same issue where the toplevel hangs after loading camlp4 - I load camlp4 with topfind in utop.

_My .ocamlinit that produces the freeze:_

``` ocaml
let () =
  try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
  with Not_found -> ()
;;
#use "topfind" ;;
#camlp4o ;;
```

I have also tried to `#require "camlp4";;` etc before calling `#camlp4o`, and using `ocaml` instead of `utop`.

**Comment by ghost** [comment]
This should be fixed. I'll do a release soon.
