### ISSUE TITLE
camlp4 / toplevel bug

### ISSUE THREAD

**Issue by xiey8** [camlp4/camlp4#50]
I checked out the fix for #48 (thanks!), and the fix mostly works but seems to introduce a new bug.

In plain ocaml, I can type 2 declarations at once and send them to the top-level with 1 single ";;".  This is useful in e.g. emacs where I can send a block containing multiple declarations to ocaml at once.

```
~:> ocaml 
        OCaml version 4.02.1

# let f = 3
  let g = 5;;
val f : int = 3
val g : int = 5
# 
```

However, as soon as I add camlp4, I can now only send 1 at a time:

```
:~> ocaml
        OCaml version 4.02.1

# #load "dynlink.cma";;
# #load "camlp4o.cma";;
        Camlp4 Parsing version 4.02.1

# let f = 3
  let g = 5;;
Error: Parse error: ";;" expected after [str_item] (in [top_phrase])
# 
```

**Comment by ghost** [comment]
Indeed, I broke this while fixing #48

**Comment by xiey8** [comment]
perfect! thx a ton!
