### ISSUE TITLE
camlp4 fails to install with ocaml 4.02.1 

### ISSUE THREAD

**Issue by kfiz** [camlp4/camlp4#52]
Installing camlp4 on osx with ocaml 4.02.1 fails with:

```
File "camlp4/boot/Camlp4.ml", line 15035, characters 31-42:
Error: This record expression is expected to have type
         Parsetree.constructor_declaration
       The constructor Pcstr_tuple does not belong to type list
Command exited with code 2.
make: *** [byte] Error 10
```

Any suggestions?

Cheers

**Comment by ghost** [comment]
Are you trying to build the git of camlp4 with 4.02.1? The trunk branch follows the trunk branch of OCaml. You need to look at the 4.02 branch.

**Comment by kfiz** [comment]
That makes sense. I'll try the 4.02 branch.

**Comment by kfiz** [comment]
Worked like a charm. Sorry for the false alarm.
Cheers
