### ISSUE TITLE
Fatal error: Parmatch.set_args when compiling camlp4

### ISSUE THREAD

**Issue by xavierleroy** [camlp4/camlp4#56]
Compiling the current Camlp4 trunk (latest commit f2d62524324d903d5716d3be5c787d9dc5c43013) with the current OCaml trunk (SVN revision 15568) gives:

/usr/local/ocaml-trunk/bin/ocamlc.opt -c -g -w a -I camlp4/import -warn-error A-3 -I camlp4/config -I camlp4/boot -o camlp4/boot/Camlp4.cmo camlp4/boot/Camlp4.ml
Fatal error: Parmatch.set_args
Fatal error: exception Misc.Fatal_error

I don't know whether this is a problem with OCaml or with camlp4 or an expected incompatibility between the two trunks, so I'm reporting the issue here as well as on the OCaml bug tracker.
(See http://caml.inria.fr/mantis/view.php?id=6647)

**Comment by ghost** [comment]
I can't reproduce this error.

> /usr/local/ocaml-trunk/bin/ocamlc.opt -c -g -w a -I camlp4/import -warn-error A-3 -I camlp4/config -I camlp4/boot -o camlp4/boot/Camlp4.cmo camlp4/boot/Camlp4.ml
> Fatal error: Parmatch.set_args
> Fatal error: exception Misc.Fatal_error

There is no pre-processing involved here, camlp4/boot/Camlp4.ml is a generated .ml file in plain OCaml syntax. So I think it's a problem in the compiler.

**Comment by xavierleroy** [comment]
Yes, this is not a Camlp4 error.  Thanks for checking.  Closing this PR.
