### ISSUE TITLE
“Unbound constructor Labelled”

### ISSUE THREAD

**Issue by Hibou57** [camlp4/camlp4#81]
Both `make all` and `make` terminates with this error:

```
 File "camlp4/boot/Camlp4.ml", line 14857, characters 34-42:
 Error: Unbound constructor Labelled
 Command exited with code 2.
 make: *** [byte] Erreur 10
```

Using OCaml version 4.02.1 and the last camlp4-trunk at the time of writing.

**Comment by Hibou57** [comment]
On the contrary, building branch 4.02 is OK.

**Comment by ghost** [comment]
Yes, that is expected, see: https://github.com/ocaml/camlp4#building-from-git
