### ISSUE TITLE
Some QPL-licensed files remain

### ISSUE THREAD

**Issue by glondu** [camlp4/camlp4#83]
There are files licensed under QPL in build/, with no indication of the exception that makes it suitable for Debian. The camlp4 package has been rejected from Debian because of that. It would be much easier if these files were under the same license as the rest, i.e. LGPL with exception.

**Comment by glondu** [comment]
There is also myocamlbuild.ml under QPL.

**Comment by ghost** [comment]
And _tags also. I'll see if I can change the license of these files, otherwise I'll add the QPL with exception.

**Comment by ghost** [comment]
I got the permission to re-license these files. Done in commit 92039c755edafaeeedc081f1e472cfc3c11e7b65.

If you need a new release tell me and I'll tag one.

**Comment by glondu** [comment]
A new release would be perfect!

**Comment by ghost** [comment]
I tagged a new release: 4.02.1+3

**Comment by glondu** [comment]
Thank you for your quick reaction!
