### ISSUE TITLE
4.02.1+3 in opam?

### ISSUE THREAD

**Issue by avsm** [camlp4/camlp4#88]
I notice 4.02.1+3 was tagged, but nothing in the Changelog.  Should we put it in OPAM?

**Comment by ghost** [comment]
Compared to +2, +3  contains #83 and #84. Not sure it is worth causing a rebuild of everything using camlp4 for these.

**Comment by avsm** [comment]
Yeah, lets leave this open and batch the update when there's a +4.  Would be good to have all released versions in OPAM eventually.
