### ISSUE TITLE
Compiling camlp4 with very few memory

### ISSUE THREAD

**Issue by n-raymond** [camlp4/camlp4#89]
Hy !

I'm actually working on a robotic project using a LegoMindstorm EV3 (ARM) with a debian distribution (Ev3Dev) and Ocaml (version 4.02.1).

I would like to use the Lwt syntax extension which requires the installation of camlp4.
Unfortunately, due to the very few memory of the machine (64 MB RAM) I never succeeded in compiling it.

I tried to compile camlp4 with the opam version and by myself directly from this git repository.
Although I set the ocaml garbage collector to free memory as much as possible with the OCAMLRUNPARAM environment variable, the compilation always fails with an out of memory exception.

Do you have any ideas or suggestions to install camlp4 on this kind of machine or is that just impossible ?

Thanks

LegoMindstorm ev3 informations : http://en.wikipedia.org/wiki/Lego_Mindstorms_EV3
Ev3Dev informations : http://www.ev3dev.org

**Comment by struktured** [comment]
Have you considered using the `lwt.ppx` syntax extension which does not require `camlp4`? See https://ocsigen.org/lwt/dev/api/Ppx_lwt.

**Comment by n-raymond** [comment]
Hy struktured !
I didn't known lwt.ppx since today. I've tried it and it seems to work very well on the robot ! Therefor I will use this other approach because it's really simpler !

Thanks very much for this good advice !
