### ISSUE TITLE
ocaml 4.02.2 is not in the supported list

### ISSUE THREAD

**Issue by vvs-** [camlp4/camlp4#92]
The new 4.02.2+rc1 seems to be not supported. It breaks lots of other packages.

**Comment by edwintorok** [comment]
While 4.02.2 was called 4.02.0+trunk the corresponding camlp4 compiled fine, is there anything that has to be synchronized between 4.02.2 and camlp4 or can the version constraint in opam be bumped for camlp4.4.02.1+2?

**Comment by ghost** [comment]
Done in ocaml/opam-repository#4246
